# Generated by Django 3.2.7 on 2021-11-28 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='Cilindraje',
            new_name='cilindraje',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='Combustible',
            new_name='combustible',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='Marca',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='Modelo',
            new_name='modelo',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='Placa',
            new_name='placa',
        ),
        migrations.RenameField(
            model_name='vehiculo',
            old_name='Tipo',
            new_name='tipo',
        ),
    ]
