# Generated by Django 3.2.7 on 2021-12-11 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_auto_20211128_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idAgendamiento', models.CharField(max_length=32, unique=True)),
                ('resultado', models.CharField(max_length=500)),
                ('fechaRevision', models.DateTimeField(auto_now_add=True)),
                ('fechaActualizacion', models.DateTimeField(auto_now=True)),
                ('idVehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.vehiculo')),
            ],
        ),
    ]
