# Generated by Django 3.2.7 on 2021-12-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_auto_20211211_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='costoTotal',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
